# Generated by Django 4.1.7 on 2023-04-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_public', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')])),
            ],
        ),
    ]
