# Generated by Django 4.1.7 on 2023-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0003_questions_username_alter_questions_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.CharField(default='', max_length=150, verbose_name='Konu'),
        ),
    ]
