# Generated by Django 4.1.7 on 2023-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
