# Generated by Django 4.1.7 on 2023-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_operations_specialization_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school_type',
            field=models.CharField(choices=[('Lise', 'Lise'), ('Önlisans', 'Önlisans'), ('Lisans', 'Lisans'), ('Yüksek_Lisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], default='Lise', max_length=14, verbose_name='Eğitim Seviyesi'),
        ),
    ]
