# Generated by Django 4.1.7 on 2023-04-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_education_school_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_year']},
        ),
    ]
